# Мне стало лень их добавлять, работает только no-permissions
messages:
  give-sender: '&d▶ &fВы &7успешно выдали&f динамит {name} &7x{amount}&f игроку &7{player}'
  give-player: '&d▶ &fВы &7успешно получили&f динамит {name} &7x{amount}'
  add-custom-item: '&d▶ &fВы успешно добавили предмет {name}'
  remove-custom-item: '&d▶ &fВы успешно удалили предмет {name}'
  error-command: '&d▶ &fОшибка в выполнении команды'
  error-item: '&d▶ &fПредемет не должен быть воздухом'
  offline-target: '&d▶ &fДанный игрока сейчас не в сети'
  invalid-tnt: '&d▶ &fДанного динамита не существует'
  no-permissions: '&d▶ &fУ вас недостаточно прав'
  
  custom-items-usage: '&c▶ &fИспользование: /tnt customitems [give/add/remove] [название] [игрок] [количество]'
  custom-items-name-required: '&c▶ &fНапишите название предмета'
  custom-items-not-exists: '&c▶ &fПредмет &e{item} &fне существует'
  custom-items-remove-success: '&d▶ &fВы успешно удалили предмет &e{item} &fиз конфига'
  custom-items-player-only: '&c▶ &fДанная команда доступна только игрокам'
  custom-items-hold-item: '&c▶ &fВозьмите в руку предмет, который хотите добавить'
  custom-items-add-success: '&d▶ &fВы успешно добавили предмет &e{name} &fв конфиг'
  custom-items-config-error: '&c▶ &fОшибка получения предметов из конфига'
  custom-items-give-success: '&a▶ &fВыдан предмет &e{item} &fигроку &e{player}'
  
  give-usage: '&c▶ &fИспользование: /tnt give [динамит] [игрок] [количество]'
  give-invalid-amount: '&c▶ &fНекорректное количество предметов'
  
  givegun-usage: '&c▶ &fИспользование: /tnt givegun [игрок] [количество]'
  givegun-invalid-amount: '&c▶ &fНекорректное количество предметов'
  givegun-success: '&a▶ &fТнт пушка успешно выдана игроку &e{player} &fx{amount}'
  
  rune-give-usage: '&c▶ &fИспользование: /tnt runegive [руна] [игрок] [количество]'
  rune-not-found: '&c▶ &fРуна &e{rune} &fне найдена'
  rune-give-sender: '&a▶ &fВы выдали руну &e{rune} &fx{amount} &fигроку &e{player}'
  rune-give-player: '&a▶ &fВы получили руну &e{rune} &fx{amount}'
  invalid-amount: '&c▶ &fНекорректное количество'
  player-only-command: '&c▶ &fДанная команда доступна только игрокам'

settings:
  # Отключает взрыв предметов
  disable_item_explosion: true
  # Отключает взрыв спавнеров
  disable_spawner_explosion: true
  # Отключает взрыв защитных блоков
  disable_protection_blocks_explosion: true

  default_custom_name:
    visible: true
    name: '&7Динамит'


runes_info_lore: '&8Улучшения:'

runes:
  # Накладывает зелье эффекты на цель
  effects:
    rune_type: EFFECTS
    display_name: '&#FF5555Руна эффектов'
    cost: 10

    # Настройки предмета руны
    item:
      material: NETHER_STAR
      display_name: '&#FF5555Руна светлячок'
      lore:
        - ''
        - '&7Применение:'
        - '&8 • &fСовместите с динамитом, чтобы применить'
        - '&8 • &fНакладывает эффект свечения на всех игроков в радиусе 20 блоков'
        - ''
      glow: true

    effects:
      # ЭФФЕКТ:ДЛИТЕЛЬНОСТЬ(тики):СИЛА
      potions:
        - "GLOW:100:2"

      # Цель эффектов:
      # PLAYERS - только игроки
      # ENTITIES - только мобы (кроме игроков и ТНТ)
      # ALL - все живые существа
      target: "PLAYERS"

      # Когда применять эффекты:
      # PRIME - при активации динамита
      # EXPLOSION - при взрыве
      give_action: "EXPLOSION"

      # Радиус действия эффектов (в блоках)
      radius: 20

  # Отключает гравитацию у динамита
  gravitation:
    rune_type: GRAVITATION
    display_name: '&#55FF55Руна невесомости'
    cost: 10

    item:
      material: FEATHER
      display_name: '&#55FF55Руна невесомости'
      lore:
        - ''
        - '&7Применение:'
        - '&8 • &fСовместите с динамитом, чтобы применить'
        - '&8 • &fДинамит теряет гравитацию'
        - ''
      glow: true

  # Автоматически поджигает динамит при установке
  auto_ignite:
    rune_type: AUTO_IGNITE
    display_name: '&#FFAA00Руна автоподжига'
    cost: 10

    item:
      material: FLINT_AND_STEEL
      display_name: '&#FFAA00Руна автоподжига'
      lore:
        - ''
        - '&7Применение:'
        - '&8 • &fСовместите с динамитом, чтобы применить'
        - '&8 • &fДинамит загорается сразу при установке'
        - ''
      glow: true

  # Изменяет скорость и направление полета динамита
  ascension:
    rune_type: ASCENSION
    display_name: '&#FFD700Руна вознесения'
    cost: 10
    item:
      material: FIREWORK_ROCKET
      display_name: '&#FFD700Руна вознесения'
      lore:
        - ''
        - '&7Применение:'
        - '&8 • &fСовместите с динамитом, чтобы применить'
        - '&8 • &fДинамит взлетает высоко в воздух'
        - ''
      glow: true
    velocity:
      upward: 2.5
      random_direction: false
      horizontal_spread: 0.3


tnt_gun:
  blocked_slots: [0,1,2,3,5,6,7,8]
  blocked_item:
    material: RED_STAINED_GLASS_PANE
    display_name: '&f  '
  item:
    material: DISPENSER
    glow: true
    display_name: '&#FB6868Т&#FB5C5Cн&#FB5050т&#FB4444-&#FB3838П&#FB4444у&#FB5050ш&#FB5C5Cк&#FB6868а'
    lore:
      - ''
      - '&8Особенности:'
      - '&7 - &#E7E7E7запускает &#FB3838летящий динамит'
      - '&0.&7   &#E7E7E7со скоростью &#FB3838до 5 блоков за секунду&#E7E7E7;'
      - '&7 - &#E7E7E7при запуске, сохраняет свойства'
      - '&0.&7   &#FB3838особых динамитов и пиротехники;'
      - '&7 - &#E7E7E7можно сломать в чужом привате.'
      - ''
  speed: 1.0
  region_break: true