name: SunTNT
main: ru.loper.suntnt.SunTNT

version: '${version}'
api-version: '1.16'

author: Loper

depend:
  - SunCore
softdepend:
  - ProtectionStones
  - WorldGuard
  - SunMysteriousEggs
  - SunHolyGoldSpawner
