# Мне стало лень их добавлять, работает только no-permissions
messages:
  give-sender: '&d ▶ &fВы &7успешно выдали&f динамит {name} &7x{amount}&f игроку &7{player}'
  give-player: '&d ▶ &fВы &7успешно получили&f динамит {name} &7x{amount}'
  add-custom-item: '&d ▶ &fВы успешно добавили предмет {name}'
  remove-custom-item: '&d ▶ &fВы успешно удалили предмет {name}'
  error-command: '&d ▶ &fОшибка в выполнении команды'
  error-item: '&d ▶ &fПредемет не должен быть воздухом'
  offline-target: '&d ▶ &fДанный игрока сейчас не в сети'
  invalid-tnt: '&d ▶ &fДанного динамита не существует'

  no-permissions: '&d ▶ &fУ вас недостаточно прав'

settings:
  # Отключает взрыв предметов
  disable_item_explosion: true
  # Отключает взрыв спавнеров
  disable_spawner_explosion: true

  default_custom_name:
    visible: true
    name: '&7Динамит'