name: SunTNT
version: '1.3.0-RELEASE'
main: ru.loper.suntnt.SunTNT
author: Loper
api-version: '1.16'
depend:
  - SunCore
softdepend:
  - SunProtectionStones
  - WorldGuard
  - HolyLiteUtils

commands:
  suntnt:
    aliases:
      - tnt
