name: SunTNT
version: '1.2-RELEASE'
main: ru.loper.suntnt.SunTNT
author: Loper
api-version: '1.16'
depend:
  - SunCore
softdepend:
  - SunProtectionStones
commands:
  suntnt:
    aliases:
      - tnt
