name: SunTNT
version: '1.6.1-RELEASE'
main: ru.loper.suntnt.SunTNT
author: Loper
api-version: '1.16'
depend:
  - SunCore
softdepend:
  - ProtectionStones
  - WorldGuard
  - SunMysteriousEggs
  - SunHolyItems
